### ISSUE TITLE
"Widened" related models

### ISSUE THREAD

**Issue by beechnut** [stevenbarragan/julia_builder#6]
Hi, Steven. I'm interested in sharing a use case of mine, and contributing to this project as a way to solve it.

I'm looking to export records to CSV, but including related models by widening them in the same row. (I've been told "widen" is the technical term for this.)

For example, if the Project model has many Team Members, my goal is to export a CSV that looks like this:

```
name,team_member_1_name,team_member_1_handle,team_member_2_name,team_member_2_handle
Julia Builder,Steven,stevenbarragan,Bryan,bry
Matt's Project,Matt,beechnut,,
```

Is this something you'd be open to seeing Julia Builder support? And if so, how can I get started on this enhancement? Thanks.

**Comment by beechnut** [comment]
I've been thinking about what the syntax might look like.

``` ruby
class ProjectCsv < Julia::Builder
  column :name
  # Looks for a Julia::Builder class named TeamMember or TeamMemberCsv
  # and serializes the object/collection using that class when nesting
  has_many :team_members
  #=> team_member_names,team_member_handles
  #=> Steven;Bryan,stevenbarragan;bry

  has_one :creator # Looks for CreatorCsv, uses when serializing

  has_many :team_members, separator: '|' # can override default separator
  #=> team_member_names,team_member_handles
  #=> Steven|Bryan,stevenbarragan|bry

  # Widens the attributes as columns, and starts counting at 1 instead of 0 (default).
  has_many :team_members, widen: true, index: 1
  #=> team_member_1_name,team_member_1_handle
  #=> Steven,stevenbarragan

  # Can pass a proc or lambda to index widening on anything else.
  has_many :team_members, widen: true, index: -> { "#{id}_of_#{TeamMember.count}" }
  #=> team_member_112_of_9000_name,team_member_112_of_9000_handle
  #=> Steven,stevenbarragan

  # If the Julia::Builder class is named something different, pass it explicitly
  has_many :team_members, class_name: 'ProjectTeamMemberCsv'
end

class TeamMemberCsv < Julia::Builder
  columns :name, handle: :username
end
```

**Comment by stevenbarragan** [comment]
Hi,

Yes, PR are welcome, and I'm more than happy to help.

First of all I would like to do a quick list of all the features you're listing of, and tackle one by one.

**Comment by stevenbarragan** [comment]
I think the first one would be the `has_one`, and we can iterate form here.
- **has one**: it'd be like a csv-inception
  
  ``` ruby
  class CsvBuilder::Project
    has_one :creator
    # sends `project.creator` to CsvBuilder::Creator's csv and concatenates
    # the result to main csv
    # it uses CsvBuilder::Creator's columns names
  end
  ```
  - We could add support to specify `class_name`
  
  ``` ruby
  has_one :creator, class_name: 'User'
  # sends `project.creator` to CsvBuilder::User's csv and concatenates
  # the result to main csv
  ```

@beechnut What do you think?

**Comment by beechnut** [comment]
This looks great -- definitely more manageable than starting with `has_many`. Should I get us started by writing some tests?

(While I'm decently experienced writing Ruby, esp. in web frameworks, this is my first time contributing to a gem in a non-trivial way.)

**Comment by stevenbarragan** [comment]
Yes, writing some test for the `has_one` method and then make the test pass. If you want to I cant take a look at your branch and help with it.

**Comment by stevenbarragan** [comment]
closing due inactivity, feel free to contact me if you need more help.
