### ISSUE TITLE
Using helpers inside builder

### ISSUE THREAD

**Issue by dimoreira** [stevenbarragan/julia_builder#8]
How can one use a Rails helper inside the builder class?
I already tried to include the helper but this didn't work for me.

My example:

``` ruby
class UserCreditsCSVBuilder < Julia::Builder
    include ActionView::Helpers::NumberHelper

    column "Value" do |c|
        number_to_currency c.amount
    end
end
```

**Comment by beechnut** [comment]
While I would have expected `include` to be the right inheritance method, I tried `extend` and it worked:

``` ruby
class DevelopmentCsv < Julia::Builder
  extend ActionView::Helpers::DateHelper

  column "Value" do |c|
    time_ago_in_words c.created_at
  end
end

DevelopmentCsv.build([Development.first])
#=> "Value\nabout 20 hours\n"
```

I assume this has something to do with the DSL-style syntax, since other objects in my app (like presenters) which use standard method definition, include the functionality correctly using `include`.

``` ruby
class EditPresenter < Burgundy::Item
  include ActionView::Helpers::DateHelper
  def time_ago
    "#{time_ago_in_words(created_at)} ago"
  end
end
```

**Comment by stevenbarragan** [comment]
@dimoreira `extend` will do the job for now (thanks @beechnut), but you're right, it should be `include`, I'll keep this issue open in order to fix it.

**Comment by dimoreira** [comment]
@beechnut @stevenbarragan Great guys. I will try `extend` for now. And keep an eye on this thread to see updates on code semantics.

Thanks
